### ISSUE TITLE
Is there a way to create a "super" user that can access any subdomain?

### ISSUE THREAD

**Issue by toymachiner62** [noiseunion/devise-basecamper#10]
I'm trying to allow my user which is a "Super" user, to login to any subdomain. I'm unable to come up with a solution to this.

Do you know if this is possible using devise-basecamper?

**Comment by noiseunion** [comment]
We haven't tested a scenario like this.  I would think that it would be a bit tricky since the user lookup is scoping to the subdomain field.  

The "easy" way to do something like this, which is how we have approached this issue so far, is to automatically add a user to each account right after creation.  We do this programmatically since it is a repetitive thing.  This way we always have a user under each account.  We will then flag this user so that the app removes the ability for anyone in the account to delete this "super" user. 

I would also recommend looking at this solution (which is the one we ultimately want to implement in our products for support purposes).

https://github.com/plataformatec/devise/wiki/How-To:-Sign-in-as-another-user-if-you-are-an-admin

Hope that helps out some.  If you want to take a stab at getting things to work differently, please do and submit a pull request.  More help in expanding how devise-basecamper works is always appreciated!

**Comment by toymachiner62** [comment]
If you programatically add a user to each account, do you have a preferred method for naming the user since you can't have duplicate users created?

**Comment by noiseunion** [comment]
you can't have duplicate users under the **same account**.  devise-basecamper automatically handles scoping things so you should be able to create the same user once under **different accounts**.  

We just use our support email for the username.

**Comment by toymachiner62** [comment]
I must not quite be understanding. If i create a user called "admin-user" and it's account_id is 1, would i create a user called "admin-user2" for account_id 2?

I'm trying to think of the solution you were referring to by this from your first response:

"The "easy" way to do something like this, which is how we have approached this issue so far, is to automatically add a user to each account right after creation"

**Comment by noiseunion** [comment]
how about some code. :)

``` ruby
class user < ActiveRecord::Base
    devise :database_authenticatable,
                :basecamper

    ## Associations ---------------------------------------
    belongs_to :account
end
```

``` ruby
class account < ActiveRecord::Base
    ## Associations --------------------------------------
    has_many :users

    ## Callbacks ------------------------------------------
    after_create :setup_support_user!

    ## Methods -------------------------------------------

    private # -----------------------------------------------

    # This will automatically create a user under the account that can be used
    # by your organization to login.  Same username/password for every account.
    # Of course, putting your password in here is not a recommended practice, so maybe move this to an environment variable or something.
    def setup_support_user!
        self.users.create({ :username => "support", :email => "support@example.com", :password => "reallyhardpassword", :password_confirmation => "reallyhardpassword" } )
    end
end
```

So with this example, every time an account is created, your "super" user is created automatically under the new account.  Your super user will always have the same username, email and password.  This is allowed, because the user is unique to the account.

Does that help?

**Comment by toymachiner62** [comment]
Yes it does very much. I could have sworn that i've tried to create the same user as an existing one, but for a different account and it didn't work. I will try again and post back here though.

**Comment by noiseunion** [comment]
Hey @toymachiner62 did you make any progress?  Just want to check in. :)

**Comment by toymachiner62** [comment]
I tried to add another record for my super user with a different account id and i got an error because of a unique index on the users table on the email column.

**Comment by toymachiner62** [comment]
I don't know if my indexes are setup correctly and i'm not sure if that was something that was supposed to take place by this gem or if i was supposed to do it manually.

My schema.rb file has these indexes:
`add_index "users", ["authentication_token"], :name => "index_users_on_authentication_token", :unique => true
  add_index "users", ["confirmation_token"], :name => "index_users_on_confirmation_token", :unique => true
  add_index "users", ["email"], :name => "index_users_on_email", :unique => true
  add_index "users", ["reset_password_token"], :name => "index_users_on_reset_password_token", :unique => true
  add_index "users", ["unlock_token"], :name => "index_users_on_unlock_token", :unique => true`

**Comment by noiseunion** [comment]
You might need to remove the default validations that devise puts in.  Remove "validatable" from your devise declaration in the model.

You will have to write your own validations to make up for the missing defaults, but then you can customize it.

**Comment by noiseunion** [comment]
forgot to mention, you can then write your unique validations to scope to the account_id.  This actually would be a good update for the basecamper gem to do automatically...might have to look into that. :)

**Comment by noiseunion** [comment]
you will want to drop the email index and add a new one.  The one you have was generated by Devise.  The new one should index the email with the account_id with the unique flag.

**Comment by toymachiner62** [comment]
Works like a charm now. As a suggestion, it may be helpful to add this to your readme. Thanks for all your help.
